name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Check directory1
      run: ls /home/runner/work/thieves-garden/

    - name: Check directory2
      run: ls /home/runner/work/thieves-garden

    - name: Check directory3
      run: ls /home/runner/work/thieves-garden/thieves-garden/package.json

    - name: Build and Deploy React app to GitHub Pages
      uses: omkartapale/react-deployment-gh-pages@v1.0.0
